Feat(ethers): retrieve and decode functions for MessageSendReaquested event
equito-network/equito-sdk pull request #23
Opened 2024-08-09 13:38 UTC by k-gunjan

added following new functions:

- getMessageAndDataByTxHash
- decodeLog_MessageSendRequested

Update deliverAndExecute function to return TxReceipt

2024-08-16 12:41 UTC, thatsimo requested changes

2024-08-16 12:41 UTC, thatsimo commented on packages/ethers/src/router/get-message-and-data-by-tx-hash.ts
> +export async function getMessageAndDataByTxHash(provider: AbstractProvider, routerContractAddress: string, txHash: string): Promise<{ message: EquitoMessage, messageData: string } | null> {
```suggestion
export async function getMessageAndDataByTxHash(provider: AbstractProvider, routerContractAddress: string, txHash: string): Promise<{ message: EquitoMessage, messageData: string }> {
```

i see it never returns null cause you throw

2024-08-16 12:41 UTC, thatsimo commented on packages/ethers/src/router/decode-log-message-send-requested.ts
> +export function decodeLog_MessageSendRequested(data: string, topics: readonly string[]): { message: EquitoMessage, messageData: string } | null {
```suggestion
export function decodeLog_MessageSendRequested(data: string, topics: readonly string[]): { message: EquitoMessage, messageData: string } {
```

update doc as well

2024-08-16 13:11 UTC, muraca requested changes

2024-08-16 13:11 UTC, muraca commented on packages/ethers/src/router/get-message-and-data-by-tx-hash.ts
> +export async function getMessageAndDataByTxHash(provider: AbstractProvider, routerContractAddress: string, txHash: string): Promise<{ message: EquitoMessage, messageData: string } | null> {
as a transaction might contain multiple MessageSendRequested events, this function should return a list of messages and be called `getMessagesByHash`

2024-08-16 14:25 UTC, k-gunjan commented on packages/ethers/src/router/get-message-and-data-by-tx-hash.ts
> +export async function getMessageAndDataByTxHash(provider: AbstractProvider, routerContractAddress: string, txHash: string): Promise<{ message: EquitoMessage, messageData: string } | null> {
i have update to return null in case of no log

2024-08-16 14:34 UTC, muraca requested changes

2024-08-16 14:34 UTC, muraca commented on packages/ethers/src/router/get-message-and-data-by-tx-hash.ts
> +export async function getMessagesByHash(
sorry for the mistake, I meant `getMessagesByTxHash`

2024-08-16 14:34 UTC, muraca commented on packages/ethers/src/router/get-message-and-data-by-tx-hash.ts
> +): Promise<MessageAndData[] | null> {
This should not return null: either an array, empty where there's no match, or throw an error when there's some mistake, eg transaction not found.

2024-08-16 14:34 UTC, muraca commented on packages/ethers/src/router/get-message-and-data-by-tx-hash.ts
> +        }
this part should be removed

2024-08-16 14:34 UTC, muraca commented on packages/ethers/src/router/get-message-and-data-by-tx-hash.ts
> +        return messages.length > 0 ? messages : null;
this should return messages as is

2024-08-16 16:36 UTC, thatsimo requested changes

2024-08-16 16:36 UTC, thatsimo commented on packages/ethers/src/router/get-message-and-data-by-tx-hash.ts
> +        return messages.length > 0 ? messages : null;
```suggestion
    // Create an Interface instance to decode the logs
    const iface = new Interface(routerAbi);
    return receipt.logs.flatMap((log) => {
      // Filter logs for the router contract address
      if (log.address.toLowerCase() === routerContractAddress.toLowerCase()) {
        try {
          const parsedLog: LogDescription | null = iface.parseLog(log);
          if (parsedLog && parsedLog.name === "MessageSendRequested") {
            const message: EquitoMessage = parsedLog.args.message;
            const messageData: string = parsedLog.args.messageData;
            return [{ message, messageData }];
          }
        } catch (parseError) {
          throw new Error(`Failed to parse log: ${parseError}`);
        }
      }
      return [];
    });
```

do this instead

2024-08-19 08:00 UTC, k-gunjan commented on packages/ethers/src/router/get-message-and-data-by-tx-hash.ts
> +        return messages.length > 0 ? messages : null;
this is a great suggestion , thanks

2024-08-19 08:45 UTC, muraca approved these changes
great job overall

2024-08-19 08:45 UTC, muraca commented on packages/ethers/src/router/decode-log-message-send-requested.ts
> +export function decodeLog_MessageSendRequested(data: string, topics: readonly string[]): { message: EquitoMessage, messageData: string } {
@thatsimo just keep an eye on this method's name.
Moreover I think the formatter should break this line into multiple. @k-gunjan can you try to format with prettier here?

2024-08-19 08:59 UTC, thatsimo commented on packages/ethers/src/router/decode-log-message-send-requested.ts
> +export function decodeLog_MessageSendRequested(data: string, topics: readonly string[]): { message: EquitoMessage, messageData: string } {
@muraca nice point, yes let's keep camelCase format. in this case let's use `decodeLogMessageSendRequested`

2024-08-19 09:17 UTC, muraca commented on packages/ethers/src/router/decode-log-message-send-requested.ts
> +export function decodeLog_MessageSendRequested(data: string, topics: readonly string[]): { message: EquitoMessage, messageData: string } {
@thatsimo what about the return type? Should we introduce a more complex EquitoMessageWithData type, or do we already have it?

2024-08-19 10:22 UTC, thatsimo commented on packages/ethers/src/router/decode-log-message-send-requested.ts
> +export function decodeLog_MessageSendRequested(data: string, topics: readonly string[]): { message: EquitoMessage, messageData: string } {
correct, @k-gunjan let's add a new documented type in `packages/core/src/types/message.ts`

`export type EquitoMessageWithData = {
  message: EquitoMessage;
  messageData: Hex;
};`

i notice that the types in this file are not documented, please add doc comments as well

2024-08-19 11:58 UTC, thatsimo approved these changes

2024-08-19 11:58 UTC, merged